// 用户数据
export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const CLEAR_USER_DETAIL = 'CLEAR_USER_DETAIL';
export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';
export const ADD_USER_POST_COUNT = 'ADD_USER_POST_COUNT';

// 文章分类
export const SET_CATEGORY_MAP = 'SET_CATEGORY_MAP';
export const SET_CATEGORY_IDS = 'SET_CATEGORY_IDS';
export const ADD_CATEGORY_POST_COUNT = 'ADD_CATEGORY_POST_COUNT';



// 文章
export const SET_POST_IDS = 'SET_POST_IDS';
export const ADD_POST_TO_BRIEF_MAP = 'ADD_POST_TO_BRIEF_MAP';
export const ADD_POST_TO_DETAIL_MAP = 'ADD_POST_TO_DETAIL_MAP';

// export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';
// // 评论
// export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';