// 用户数据
export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const CLEAR_USER_DETAIL = 'CLEAR_USER_DETAIL';
export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';
export const ADD_USER_POST_COUNT = 'ADD_USER_POST_COUNT';

export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';

// 其他用户
export const SET_OTHER_USER_DETAIL = 'SET_OTHER_USER_DETAIL';


// 文章分类
export const SET_CATEGORY_MAP = 'SET_CATEGORY_MAP';
export const SET_CATEGORY_IDS = 'SET_CATEGORY_IDS';
export const ADD_CATEGORY_POST_COUNT = 'ADD_CATEGORY_POST_COUNT';

// 文章
export const SET_POST_IDS = 'SET_POST_IDS';
export const SET_USER_POST_IDS = 'SET_USER_POST_IDS';
export const ADD_POST_TO_BRIEF_MAP = 'ADD_POST_TO_BRIEF_MAP';
export const ADD_USER_POST_TO_BRIEF_MAP = 'ADD_USER_POST_TO_BRIEF_MAP';
export const ADD_POST_TO_DETAIL_MAP = 'ADD_POST_TO_DETAIL_MAP';
export const ADD_COMMENT_ID_TO_POST_DETAIL = 'ADD_COMMENT_ID_TO_POST_DETAIL';
export const ADD_COMMENT_COUNT_IN_POST_DETAIL = 'ADD_COMMENT_COUNT_IN_POST_DETAIL';
export const ADD_REPLY_TO_POST_DETAIL = 'ADD_REPLY_TO_POST_DETAIL';
export const TOGGLE_BRIEF_POST_LIKE = 'TOGGLE_BRIEF_POST_LIKE';
export const TOGGLE_USER_BRIEF_POST_LIKE = 'TOGGLE_USER_BRIEF_POST_LIKE';

// 评论
export const ADD_COMMENTS_TO_COMMENT_MAP = 'ADD_COMMENTS_TO_COMMENT_MAP';
export const ADD_REPLY_ID_TO_COMMENT_DETAIL_MAP = 'ADD_REPLY_ID_TO_COMMENT_DETAIL_MAP';
export const TOGGLE_COMMENT_LIKE = 'TOGGLE_COMMENT_LIKE';
export const SET_USER_COMMENT_IDS = 'SET_USER_COMMENT_IDS';
export const ADD_USER_COMMENT_TO_BRIEF_MAP = 'ADD_USER_COMMENT_TO_BRIEF_MAP';
export const TOGGLE_USER_COMMENT_LIKE = 'TOGGLE_USER_COMMENT_LIKE';

// 回复
export const ADD_REPLIES_TO_REPLY_MAP = 'ADD_REPLIES_TO_REPLY_MAP';
export const ADD_REPLY_TO_REPLY_MAP = 'ADD_REPLY_TO_REPLY_MAP';
export const TOGGLE_REPLY_LIKE = 'TOGGLE_REPLY_LIKE';