export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const CLEAR_USER_DETAIL = 'CLEAR_USER_DETAIL';
export const CLEAR_USER_LOGIN = 'CLEAR_USER_LOGIN';
